### PR TITLE
Fix exec command for new go-critic release

### PR DESCRIPTION
**Pull request by korjavin**
Improved request instead of #32

### CODE REVIEW

**Comment by davidpfarrell** [comment]
So I modified my local config to use your repository to test out your change.

#### Regarding the `-disable` and `-enable` options:

I see that running `gocritic` with no args does show your command line as one of the examples:

```
$ gocritic 
not enough arguments, expected sub-command name

Supported sub-commands:
	check - run linter over specified targets
		$ gocritic check -help
		$ gocritic check -enable='paramTypeCombine,unslice' strings bytes
		$ gocritic check -v -enable='#diagnostic' -disable='#experimental,#opinionated' ./...
	version - print linter version
		$ gocritic version
	doc - get installed checkers documentation
		$ gocritic doc -help
		$ gocritic doc
		$ gocritic doc checkerName
```

Looking further, we can see the list of default checks here:

* https://go-critic.github.io/overview

We see:

> Checkers from the “diagnostic” group
> All diagnostics are enabled by default (unless it has “experimental” tag).

> Checkers from the “style” group
> Only non-opinionated style checks are enabled by default.

Manually reviewing each enabled-by-default check confirms that no checks that are enabled by default fall into either the "experimental" or "opinionated" categories.

BUT having an `-enable` argument implicitly disables everything that is not in the argument.
In this PR's case, having `-enable="#diagnostic"` implicitly disables all `#style` checks

Q: Did you mean to have Style checks disabled (even non-opinionated ones) ?  Would this be considered on-par with the previous version of `go-critic`?

**My thoughts:** Since `diagnostic` appears to be enabled by default, and both `experimental` and `opinionated` appear to be disabled by default, I suspect we don't need to specify any `-enable` or `-disable` arguments.

#### Regarding the `-v` argument

Looks like the `-v` argument generates a TON of debug reporting:

**NOTE:** Interesting, it appears that `pre-commit` hides all debug output unless the check reports an actual result.   I don't currently have any `#diagnostic` checks failing in my test repo, so I included the `#style` checks so I could see what an error looks like

Pre-commit check with `-v` present and `#style` added to `-enable` list:

```
$ pre-commit

go-critic................................................................Failed

...
	debug: switchTrue is enabled
	debug: typeSwitchVar is enabled
	debug: underef is enabled
	debug: unlambda is enabled
	debug: unslice is enabled
./path/to/file.go:52:10: elseif: can replace 'else {if cond {}}' with 'else if cond {}'
./path/to/file.go:96:10: elseif: can replace 'else {if cond {}}' with 'else if cond {}'
./path/to/file.go:52:10: elseif: can replace 'else {if cond {}}' with 'else if cond {}'

```

Pre-commit check with `-v` removed and `#style` added to `-enable` list:

```
$ pre-commit

go-critic................................................................Failed
./path.to/file.go:52:10: elseif: can replace 'else {if cond {}}' with 'else if cond {}'
./path.to/file.go:96:10: elseif: can replace 'else {if cond {}}' with 'else if cond {}'
./path.to/file.go:52:10: elseif: can replace 'else {if cond {}}' with 'else if cond {}'
```

**My Thoughts:** I suspect we don't need the `-v` argument

#### Regarding `./...`

I is unclear to me what the best practice is for using `.` over `./..` with go-related git hooks.

I will say that, since my code lives deep under the root folder, that having `./...` worked for me, while the original script's `.` generated no messages.

**My Thoughts:** Leave `./...`

**Comment by korjavin** [comment]
I agree with you. Thank you.

Sorry for being quiet, I just was really busy, and thank you again for you systematic approach.

**Comment by korjavin** [comment]
Regarding ./...
I think it is best practice for go-related tools.
But feel free to change it if you wish.

**Comment by davidpfarrell** [comment]
This Look good to me.  A couple of notes:

* I have no authority over this project - I'm just a drive-by reviewer :)

* I didn't realize, but just confirmed, that the `pre-commit-config.yaml` only supports tags/revisions on the `master` branch ... So your new PR being on branch `go-critic` means I can't directly test it (apparently I was testing your previous PR which is on `master`) ... 

Attempt to update from `0.4.2` (on `master`) to `0.4.3` (on branch `go-critic`):
```
$ pre-commit autoupdate

Updating git://github.com/korjavin/pre-commit-golang...
[INFO] Initializing environment for git://github.com/korjavin/pre-commit-golang.
[INFO] Initializing environment for git://github.com/korjavin/pre-commit-golang.
updating v0.4.3 -> v0.4.2.
```

Notice is forces a downgrade back to `0.4.2`.

You don't have to change anything, as having it on a branch doesn't affect the PR itself, just something to know for future reference if you're ever working your own pre-commit plugins.

**Comment by korjavin** [comment]
>Notice is forces a downgrade back to 0.4.2.
Wow! What  a move!
I would never expect that.
I merged it to master just to check.

**Comment by dnephin** [comment]
Cool, this looks like it matches the docs, so LGTM

**Pull request merged**
