### PR TITLE
Update go-critic section in README.md

### PR DESCRIPTION
**Pull request by davidpfarrell**
A recent PR ( #33 ) was merged, correcting the go-critic script.  This PR brings  README.md into alignment with that change.

### CODE REVIEW

**Comment by davidpfarrell** [comment]
@korjavin Can you take a quick look at this?

**Comment by korjavin** [comment]
Lgtm

**Comment by davidpfarrell** [comment]
Thanks @korjavin.

@dnephin : Assuming this might get merged : Please also cut a new release version (`v0.3.4`?)

**Comment by dnephin** [comment]
Thanks! I tagged v0.3.4

**Pull request merged**
