### PR TITLE
Fix exec command for new go-critic release

### PR DESCRIPTION
**Pull request by korjavin**
Seems like go-critic changed its args.

### CODE REVIEW

**Comment by davidpfarrell** [comment]
I came to to see if anyone noticed this and glad to see there' s already a PR for it !

I might recommend opening an issue too then referencing it here?

Q: I see there's a lot more to your `go-critic` fix than just `"check-project" -> "check"`.   Did go-critic also change their default behavior, which these changes bring back to par?  If not, I would keep the goal of this PR as keeping par with previous behavior.

Q: Is the `golangci-lint` mod related to the `go-critic` command change?  Although its convenient, if its not related, I would recommend a separate PR.

**Comment by korjavin** [comment]
1. Yup, As far as I understood go-critic demans now list of features.
2. Sorry, it was a mistake, it's not related.

**Comment by davidpfarrell** [comment]
> 1. Yup, As far as I understood go-critic deman[d]s now list of features.

I see.  I never used `golangci-lint` before trying it from this plugin a few days ago so I'm not fully up to speed on previous behavior.

It does seem to run without any extra args, i.e. If I fix the shell script or just run it manually on the CLI.

Just the same, If you feel the args help the new version match the behavior of the previous version, I would keep them in the PR for further discussion.

> 2. Sorry, it was a mistake, it's not related.

Q: Did you close this due to the `golangci-lint` change being in it?  You can safely remove those changes from the PR and keep the `go-critic` fix moving forward.

Thanks for the reply.

**Comment by korjavin** [comment]
I created a separate PR.

**Comment by davidpfarrell** [comment]
> I created a separate PR.

Yeah I prolly should have looked for one ...

**Pull request closed without merging**
